[workspace]
resolver = "2"
members = [
  "src/expression_lib",
  "pyo3-polars",
  "pyo3-polars-derive",
]

[workspace.dependencies]
polars = { version = "0.33.2", default-features = false }
polars-core = { version = "0.33.2", default-features = false }
polars-ffi = { version = "0.33.2", default-features = false }
polars-plan = { version = "0.33.2", default-feautres = false }
polars-lazy = { version = "0.33.2", default-features = false }
